version: '3.5'
services:
  ansible:
    container_name: ansible
    build: 
      context: .
      dockerfile: ansible.dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src:/src
    networks:
      - gitlab

networks:
  gitlab: