---
  - name: "Playing with Ansible and Git"
    hosts: localhost
    connection: local 
    tasks:

    - name: Get info on docker host
      docker_host_info:
      register: result

    - debug: var=result